{% set name = "geedim" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geedim-{{ version }}.tar.gz
  sha256: d9229ee519c32201efcc39b0dbd889398ef0070e67eba1c3a0e06e2bcc5109d5

build:
  entry_points:
    - geedim=geedim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7,<9
    - earthengine-api >=0.1.2,<1
    - pandas >=1.1,<2
    - python >=3.6
    - requests >=2.2,<3

test:
  imports:
    - geedim
  commands:
    - geedim --help

about:
  home: https://github.com/dugalh/geedim
  summary: Google Earth Engine image download
  license: Apache-2.0
  license_file: LICENSE
  description: |
    geedim provides a command line interface and API for searching by date,
    region, and cloud/shadow statistics. It optionally performs cloud/shadow
    masking, and cloud-free compositing. Images and composites (including
    metadata) can be downloaded, or exported to Google Drive.

extra:
  recipe-maintainers:
    - dugalh
