{% set name = "geedim" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geedim-{{ version }}.tar.gz
  sha256: cf57d5e5302582c7bb30c93abab539b362edc08e1c1bbf70511f764de68f40c4

build:
  entry_points:
    - geedim=geedim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - rasterio >=1.3.8
    - click >=8
    - tqdm >=4.6
    - earthengine-api >=0.1.379
    - requests >=2.2
    - tabulate >=0.8
test:
  imports:
    - geedim
  commands:
    - pip check
    - geedim --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/leftfield-geospatial/geedim
  summary: Search, composite, and download Google Earth Engine imagery.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    `geedim` provides a command line interface and API for searching, compositing and downloading 
    satellite imagery from Google Earth Engine (EE).  It optionally performs cloud / shadow 
    masking, and cloud / shadow-free compositing on supported collections.  Images and composites 
    can be downloaded; or exported to Google Drive, Earth Engine asset or Google Cloud Storage.  
    Images larger than the EE size limit are split and downloaded as separate tiles, then 
    re-assembled into a single GeoTIFF.

extra:
  recipe-maintainers:
    - dugalh
