{% set name = "geedim" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geedim-{{ version }}.tar.gz
  sha256: c546928cdca826d5bfe6fd21084855e6420f122621b3ea4230ae682d37fa6ece

build:
  entry_points:
    - geedim=geedim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.19
    - rasterio >=1.1
    - click >=8
    - tqdm >=4.6
    - earthengine-api >=0.1.2
    - requests >=2.2
    - tabulate >=0.8

test:
  imports:
    - geedim
  commands:
    - geedim --help

about:
  home: https://github.com/dugalh/geedim
  summary: Search, composite, and download Google Earth Engine imagery.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    `geedim` provides a command line interface and API for searching, compositing and downloading 
    satellite imagery from Google Earth Engine (EE).  It optionally performs cloud / shadow 
    masking, and cloud / shadow-free compositing on supported collections.  Images and composites 
    can be downloaded, or exported to Google Drive.  Images larger than the EE size limit are 
    split and downloaded as separate tiles, then re-assembled into a single GeoTIFF.

extra:
  recipe-maintainers:
    - dugalh
